In [1]:
import pandas as pd
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/3.25k [00:00<?, ?B/s]

data_jobs.csv: reconstructing file:   0%|          |  0.00B /  231MB

data_jobs.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [4]:
df['job_country'].value_counts().head(10)

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
Spain              25100
Singapore          23696
Sudan              21781
Netherlands        20631
Italy              17013
Name: count, dtype: int64

In [5]:
df['job_country'].isin(['Russia']).any()

np.True_

In [28]:
russia_jobs = df[df['job_country'] == 'Russia']

In [30]:
us_jobs = df[df['job_country'] == 'United States']

In [31]:
us_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,None,NaN,NaN,JPMorgan Chase & Co.,None,None
785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,None,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,None,NaN,NaN,Axelon Services Corporation,None,None
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,None,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

In [9]:
russia_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
23,Machine Learning Engineer,"PhD position in computer science (NLP, finance)",Russia,via hh.ru,Full-time,False,Russia,2023-09-30 13:52:00,False,False,Russia,None,NaN,NaN,Грешнев Олег Владимирович,"['python', 'r']","{'programming': ['python', 'r']}"
284,Data Engineer,Data Engineer (DWH Arch),Anywhere,via hh.ru,Full-time,True,Russia,2023-12-27 13:38:19,True,False,Russia,None,NaN,NaN,ФЛАУВАУ,"['python', 'go', 'sql', 'airflow', 'kafka', 's...","{'async': ['jira'], 'libraries': ['airflow', '..."
449,Data Engineer,Data Engineer,"Moscow, Russia",via hh.ru,Full-time,False,Russia,2023-02-07 13:37:23,True,False,Russia,None,NaN,NaN,Aviasales.ru,"['python', 'sql', 'scala', 'go', 'typescript',...","{'async': ['jira'], 'cloud': ['aws'], 'databas..."
541,Data Engineer,Data engineer в продукт МТС Маркетолог (Big Data),"Moscow, Russia",via hh.ru,Full-time,False,Russia,2023-03-02 13:18:53,False,False,Russia,None,NaN,NaN,"«МТС», IT","['python', 'sql', 'spark', 'kafka']","{'libraries': ['spark', 'kafka'], 'programming..."
605,Data Analyst,Data engineer / Data Scientist / Data Analyst,"Moscow, Russia",via hh.ru,Full-time,False,Russia,2023-10-13 14:10:51,False,False,Russia,None,NaN,NaN,СтандартПроект,"['python', 'sql', 'java', 'elasticsearch', 'ai...","{'databases': ['elasticsearch'], 'libraries': ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
782695,Machine Learning Engineer,Data Scientist / Machine Learning Engineer,"Krasnogorsk, Moscow Oblast, Russia",via hh.ru,Full-time,False,Russia,2023-01-17 07:15:29,False,False,Russia,None,NaN,NaN,Центр Методического Обеспечения Оптимизации Пр...,"['python', 'numpy', 'pandas', 'matplotlib', 'o...","{'libraries': ['numpy', 'pandas', 'matplotlib'..."
782772,Data Engineer,Data Engineer,"St Petersburg, Russia",via hh.ru,Full-time,False,Russia,2023-01-16 06:35:50,False,False,Russia,None,NaN,NaN,Сбер. IT,"['sql', 'c', 't-sql', 'vba', 'c#', 'java', 'sq...","{'databases': ['sql server', 'postgresql'], 'p..."
782929,Software Engineer,DevOps Engineer,"Moscow, Russia",via Trabajo.org,Full-time,False,Russia,2023-10-23 06:44:34,True,False,Russia,None,NaN,NaN,Aston,"['sql', 'nosql', 'bash', 'vmware', 'windows', ...","{'cloud': ['vmware'], 'os': ['windows'], 'othe..."
783361,Data Scientist,Data инженер (YAPPY),Anywhere,via hh.ru,Full-time,True,Russia,2023-10-23 06:44:34,True,False,Russia,None,NaN,NaN,Rutube,"['sql', 'python', 'postgresql', 'airflow', 'ha...","{'databases': ['postgresql'], 'libraries': ['a..."
785051,Data Scientist,Старший инженер Hadoop,"Moscow, Russia",via BeBee Россия,Full-time,False,Russia,2023-09-12 06:32:25,True,False,Russia,None,NaN,NaN,МегаФон,"['python', 'hadoop', 'spark', 'airflow', 'kafk...","{'libraries': ['hadoop', 'spark', 'airflow', '..."

In [11]:
russia_jobs = russia_jobs.dropna(subset= ['salary_year_avg'])

In [12]:
russia_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
244788,Cloud Engineer,ETL разработчиĸ,Russia,via GeekLink,Full-time,False,Russia,2023-11-24 07:19:48,True,False,Russia,year,280000.0,NaN,Технологическая компания,['sql'],{'programming': ['sql']}
472583,Software Engineer,SQL Developer,Russia,via GeekLink,Full-time,False,Russia,2023-12-06 14:18:56,True,False,Russia,year,320000.0,NaN,SmartBrain,None,None
499036,Data Scientist,Data scientist,Russia,via GeekLink,"Part-time, Contractor, and Temp work",False,Russia,2023-11-10 11:36:48,False,False,Russia,year,320000.0,NaN,SWS,"['python', 'sql', 'opencv', 'pytorch']","{'libraries': ['opencv', 'pytorch'], 'programm..."
515431,Data Scientist,Data Scientist / ML-инженер,Russia,via GeekLink.io,Full-time,False,Russia,2023-06-27 11:45:07,False,False,Russia,year,250000.0,NaN,DevHunt,"['python', 'sql', 'postgresql', 'oracle', 'pan...","{'cloud': ['oracle'], 'databases': ['postgresq..."

In [24]:
russia_jobs.groupby(['job_title_short'])['salary_year_avg'].agg('median')

job_title_short
Cloud Engineer       280000.0
Data Scientist       285000.0
Software Engineer    320000.0
Name: salary_year_avg, dtype: float64

In [32]:
us_jobs = us_jobs.dropna(subset= ['salary_year_avg'])

In [48]:
us_jobs.groupby(['job_title_short'])['salary_year_avg'].agg(['median', 'min', 'max', 'count']).sort_values('median', ascending= False)

                             median      min       max  count
job_title_short
Senior Data Scientist      155000.0  55000.0  475000.0   1241
Machine Learning Engineer  150000.0  44408.5  315000.0    128
Senior Data Engineer       150000.0  45000.0  375000.0   1058
Data Scientist             130000.0  30000.0  960000.0   4553
Software Engineer          130000.0  48982.0  375000.0    157
Data Engineer              125000.0  23496.0  525000.0   2915
Cloud Engineer             116100.0  42000.0  221844.0     20
Senior Data Analyst        110000.0  35360.0  425000.0    913
Business Analyst            90000.0  35000.0  387460.0    431
Data Analyst                90000.0  25000.0  375000.0   4350